### ISSUE TITLE
Combine research

### ISSUE THREAD

**Issue by fpousserot** [Atinux/api-as-a-service#2]
Combine several research fields, with the choice of operator 'AND' , 'OR', etc..

example: 

```
/api/products?name='toto'&category='mini'|category='little'
```

**Comment by atinux** [comment]
Nice proposition, I think I will add it for the next milestone.

I think this will be more like : 

<pre>
/api/products?name=toto&category=mini&category=little
</pre>

Like this, on the server-side, I get back in req.query :

<pre>
{
  name: 'toto',
  category: ['mini', 'little']
}
</pre>

This request mean *Get all the entries with name equal "toto" AND category equal "mini" OR name equal "toto" AND category equal "little".

**Comment by fpousserot** [comment]
Ok, 

But for the search name=toto OR category=mini ? how precise the operator [ && ; |l ] ?
