### ISSUE TITLE
api-as-a-service

### ISSUE THREAD

**Issue by metaphoric** [Atinux/api-as-a-service#4]
Votre article qui semblait fort intéressant http://www.atinux.fr/2012/08/04/developper-une-application-web-en-quelques-minutes/ a disparu...
Est-ce que vous auriez une copie, un tuto, une démo?

**Comment by atinux** [comment]
Si sur WebArchive : http://web.archive.org/web/20130928012633/http://www.atinux.fr/2012/08/04/developper-une-application-web-en-quelques-minutes/

**Comment by metaphoric** [comment]
Merci!
